import 'package:flutter/material.dart';
import 'package:ledger/core/constants/app_constants.dart';
import 'package:ledger/presentation/widgets/app_widgets.dart';

class ReportFooter extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Divider(height: 1, thickness: 1, color: Colors.grey),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 8.0),
           child:  SmallText(
              'Generated by ${AppConstants.appName}  on ${DateTime.now()}',
            )
          )

          
        ],
      ),
    );
  }
}
